version: "3.8"
services:
  database:
    image: postgres:alpine
    environment: 
        - POSTGRES_PASSWORD=password
    ports: 
        - 5432:5432
    volumes: 
        - .tmp/database/data:/var/lib/postgresql/data